collections:
  - common
  - purescript

excludes:
  - .cspell.json
  - README.md
  - bower.json
  - package.json
  - spago.dhall

render_context:
  project:
    name: purescript-huffman
    description: Huffman coding. Lossless data compression.
    version: 0.2.0
    verbose_name: PureScript Huffman
    repository: https://github.com/JoelLefkowitz/purescript-huffman
    codacy_id: 4934e15d76c04969af83eddea6ce5461

  author:
    author: joellefkowitz
    author_email: joellefkowitz@hotmail.com
    verbose_author: Joel Lefkowitz

clear_top_level: true
logical_grouping: true

loader_paths:
  - docs
