severity: low
exclude:
  - message: Codacy project public id
    pattern: 4934e15d76c04969af83eddea6ce5461

  - message: Package owner public ssh key
    pattern: public
    paths:
      - purs.json

  - message: Giphy links
    pattern: https://media.giphy.com/media/

  - message: Build output
    paths:
      - output/cache-db.json

  - message: Docs output
    paths:
      - generated-docs

  - message: Dependencies
    paths:
      - bower_components
      - node_modules
      - package-lock.json
      - packages.dhall
      - spago.dhall
      - venv
      - yarn-error.log
      - yarn.lock
